version: "3.4"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    restart: always
    image: postgres
    container_name: "postgres_tanfum"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tanfum-local
    volumes:
      - pgvol:/var/lib/postgresql/data
  postgres-test:
    restart: always
    image: postgres
    container_name: "postgres_tanfum_test"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tanfum-test
volumes:
  pgvol:
  pgadmin:
