version: '3.4'

services:
  fake-smtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports:
      - '25:25'
    volumes:
      - ~/fake-smtp-emails:/var/mail
  fake-smtp-web:
    image: mjstewart/fakesmtp-web:1.2
    container_name: fake-smtp-web
    ports:
      - '60500:8080'
    volumes:
      - ~/fake-smtp-emails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fake-smtp
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - '8000:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    restart: always
    image: postgres
    container_name: 'postgres_tanfum'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tanfum-local
    volumes:
      - pgvol:/var/lib/postgresql/data
  postgres-test:
    restart: always
    image: postgres
    container_name: "postgres_tanfum_test"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tanfum-test
  minio:
    image: minio/minio
    volumes:
      - v1:/export
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /export
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  v1:
  pgvol:
  pgadmin:
